services:
  mongodb:
    image: mongo:7.0.34
    container_name: jloka-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: jloka-users-db
      # Optional: Add authentication if needed
      # MONGO_INITDB_ROOT_USERNAME: admin
      # MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
    networks:
      - jloka-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  user-service:
    build:
      context: ./user-service  # Path to your user service directory
      dockerfile: Dockerfile
    container_name: jloka-user-service
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      MONGO_URL: mongodb://mongodb:27017/jloka-users-db
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - jloka-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  task-service:
    build:
      context: ./task-service  # Path to your user service directory
      dockerfile: Dockerfile
    container_name: jloka-task-service
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      MONGO_URL: mongodb://mongodb:27017/jloka-users-db
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - jloka-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
  notification-service:
    build:
      context: ./notification-service  # Path to your user service directory
      dockerfile: Dockerfile
    container_name: jloka-notification-service
    restart: unless-stopped
    ports:
      - "3002:3002"
    environment:
      MONGO_URL: mongodb://mongodb:27017/jloka-users-db
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - jloka-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s


networks:
  jloka-network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local
  mongodb_config:
    driver: local